#!/bin/bash

set -e -x

out_dir=/tmp/xen
xen_version=4.11.0
out_file_tools=viryaos-xen-tools.tar.gz
out_file_boot=viryaos-xen-boot.tar.gz
source_dir=/home/builder/src/viryaos-xen

curl -fsSLO https://downloads.xenproject.org/release/xen/$xen_version/xen-$xen_version.tar.gz
tar xvzf xen-$xen_version.tar.gz
cd xen-$xen_version
patch -p1 < /$source_dir/xen-patch
./configure --prefix=/usr                                \
    --disable-qemu-traditional                           \
    --disable-rombios                                    \
    --disable-stubdom                                    \
    --with-system-qemu=/usr/lib/xen/bin/qemu-system-i386
make -j "$(getconf _NPROCESSORS_ONLN)"
mkdir -p DESTDIR=$out_dir
make DESTDIR=$out_dir install
cp $source_dir/xenstored.initd $out_dir/etc/init.d/xenstored
chmod +x $out_dir/etc/init.d/xenstored
cp $source_dir/xenconsoled.initd $out_dir/etc/init.d/xenconsoled
chmod +x $out_dir/etc/init.d/xenconsoled
cd ..

qemu_version=2.11.2
curl -fsSLO https://download.qemu.org/qemu-$qemu_version.tar.xz
tar xvJf qemu-$qemu_version.tar.xz
cd qemu-$qemu_version
patch -p1 < $source_dir/qemu-patch
export PKG_CONFIG_PATH=$source_dir/xen/tools/pkg-config
export INST_DIR=$out_dir
./configure --prefix=/usr                                 \
    --disable-kvm                                         \
    --disable-werror                                      \
    --enable-virtfs                                       \
    --enable-xen                                          \
    --extra-cflags="-I$INST_DIR/usr/include"              \
    --extra-ldflags="-L$INST_DIR/usr/lib                  \
                     -Wl,-rpath-link=$INST_DIR/usr/lib    \
                     -L$INST_DIR/usr/lib64                \
                     -Wl,-rpath-link=$INST_DIR/usr/lib64" \
    --target-list=i386-softmmu
make -j "$(getconf _NPROCESSORS_ONLN)"
make DESTDIR=$out_dir install
mv $out_dir/usr/bin/qemu-system-i386 $out_dir/usr/lib/xen/bin/qemu-system-i386

cp $source_dir/xenqemu.initd $out_dir/etc/init.d/xenqemu
cd $out_dir

tar cvzf $out_file_tools etc/ usr/ var/
tar cvzf $out_file_boot boot/

container_output_tools="/home/builder/src/viryaos-xen/output-viryaos-xen-tools"
rm -rf $container_output_tools
mkdir $container_output_tools

container_output_boot="/home/builder/src/viryaos-xen/output-viryaos-xen-boot"
rm -rf $container_output_boot
mkdir $container_output_boot

cp $out_file_tools $container_output_tools
cp $out_file_boot $container_output_boot
